version: 1
channel: development
generatedAt: 2026-09-29T21:18:14.809Z
validatedBy: null
contracts:
  "@cosmic-arcana/sdk": 0.1.1
services:
  history-service-api:
    repository: Cosmic-Arcana/history-service-api
    image: ghcr.io/cosmic-arcana/history-service-api
    digest: sha256:1b1ada97ba073733093d55807716147151ab7841d4822489ef0fc245377eea8a
    commit: 413269755f51beae05d044dcafaae3ffe5073b1d
    tier: flow
    updatedAt: 2026-09-29T21:18:14.809Z
  tarot-service-api:
    repository: Cosmic-Arcana/tarot-service-api
    image: ghcr.io/cosmic-arcana/tarot-service-api
    digest: sha256:e0066de09a65f5487f3cedb1df03cc22f571989d0c82c78ca89ef68446d6d53e
    commit: dddb66efc321693859ed33b70f52a4107db7eb27
    tier: flow
    updatedAt: 2026-09-29T17:21:12.325Z
