version: 1
channel: development
generatedAt: 2026-09-29T15:50:00.305Z
validatedBy: null
contracts:
  "@cosmic-arcana/sdk": 0.1.1
services:
  history-service-api:
    repository: Cosmic-Arcana/history-service-api
    image: ghcr.io/cosmic-arcana/history-service-api
    digest: sha256:d71723c81b37ac4c02241cb9e9b8937a146d481d4ff933ec409e56f5aec45332
    commit: 23f9be9f061cf65a51e58b1f8b3d7a755f3e4de3
    tier: flow
    updatedAt: 2026-09-29T15:50:00.305Z
